Repository ichiro-its/shisen-app, pull requests merged in 2021-03, with the labels that each got.

#4 init interface ros2wb
  package.json
  src/App.js
  src/components/CustomAppBar.js
  src/components/CustomSnackbar.js
  yarn.lock
Labels: enhancement

#7 add ci yarn
  .github/workflows/shisenapp_ci.yml
  src/App.js
Labels: enhancement

#9 5 add linter
  .eslintrc.json
  .github/workflows/shisen_app_ci.yml
  LICENSE
  package.json
  src/App.js
  src/App.jsx
  src/App.test.js
  src/components/AppBar.jsx
  src/components/CustomAppBar.js
  src/components/CustomSnackbar.js
  src/components/Snackbar.jsx
  src/index.js
  src/index.jsx
  src/reportWebVitals.js
  src/setupTests.js
  yarn.lock
Labels: enhancement, good first issue

#11 try add homepage
  package.json
Labels: bug
